source 'https://github.com/NJHu/NJSpecs.git' # NJ 私有源
source 'https://github.com/CocoaPods/Specs.git' # 公有源


platform :ios, '10.3'
use_frameworks!

target 'NJSisVideoList_Example' do
  pod 'NJSisVideoList', :path => '../'

  target 'NJSisVideoList_Tests' do
    inherit! :search_paths

    
  end
end
